### ISSUE TITLE
Stock Droid Browser Nonfunctional

### ISSUE THREAD

**Issue by alexflanagan** [gilbitron/Ideal-Image-Slider#38]
This might be related to #31 : on the Android stock browser ("Internet") on my Galaxy S3 (Droid version 4.4.2) the 'new IdealImageSlider.Slider' call crashes with:

Uncaught TypeError: Property 'hasOwnProperty' of object object is not a function

**Comment by lianee** [comment]
I can confirm the exact same error on stock browser Android 4.3

**Comment by gilbitron** [comment]
Fixed in #81.
