### ISSUE TITLE
height didn't set properly

### ISSUE THREAD

**Issue by crossRT** [gilbitron/Ideal-Image-Slider#46]
As suggest, i didn't pass a height value to object constructor in order to let CSS handle the style. But it doesn't work, Ideal-Image-Slider override the slider style directly to the element.
Any help will be appreciated.
js:
```javascript
<script>
	var slider = new IdealImageSlider.Slider({
		selector: '#slider',
		interval: 3500,
		keyboardNav: true,
	});
	slider.addBulletNav();
	slider.start();
</script>
```
css:
```css
 #slider {
	height: 90%;
 }
```

**Comment by racse1** [comment]
@crossRT just pass `height: false`  in options.
```js
// Set height
if(this.settings.height){
	this._attributes.container.style.height = this.settings.height +'px';
}
```

**Comment by gilbitron** [comment]
Height is now responsive in v1.5.0.
