### ISSUE TITLE
How can I set the height of the div slider to be the same as the content?

### ISSUE THREAD

**Issue by antonioj1015** [gilbitron/Ideal-Image-Slider#47]
I'm using bootstrap on my site and I need the height of the div slider to be the same as the content. How can I do this?

I did this so the image is shown but the height of the div slider is always the same.
#slider a {
	background-size: contain;
	
}

If I apply &lt;div id="slider" style="overflow: hidden;"&gt; it wont work either.

**Comment by 7yl4r** [comment]
I suggest passing the height in the options when you init your slider in js.

Assuming your html structure is similar to:
```html
<div id="content-section">
  <div id="slider">
     ...slider content here...
  </div>
</div>
```

Do something like this:
```javascript
var slider = new IdealImageSlider.Slider({
    selector: '#slider',
    height: $(#content-section).height(),
});
slider.start();
```
