### ISSUE TITLE
Height not changeable by media queries

### ISSUE THREAD

**Issue by gregwillits** [gilbitron/Ideal-Image-Slider#59]
If I do not include height: in the new IdealImageSlider() options, but I DO include height in my CSS, the CSS height is not used, and the slider box defaults to 400px.

I have included media queries to change the overall size of the slider. Width is working, but height is not because the IIS appears to be inject a style="" to force the height to whatever I included at the time of creation. It appears to be not editable after that.

**Comment by gilbitron** [comment]
Height is now responsive in v1.5.0.
